$font = Monospace

general {
    hide_cursor = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2

    fade_on_empty = false
    rounding = 8

    placeholder_text = Password...
    fail_text = Authentication failed

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 52
    font_family = $font
    position = -45, -25
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 18
    font_family = $font
    position = -45, -100
    halign = right
    valign = top
}

# BATTERY
label {
    monitor =
    text = cmd[update:30000] ~/.config/hypr/scripts/hyprlock/battery-status.sh
    font_size = 18
    font_family = "JetBrainsMono Nerd Font"
    position = -45, -140
    halign = right
    valign = top
}

# MEDIA TITLE
label {
    monitor =
    text = cmd[update:5000] ~/.config/hypr/scripts/hyprlock/media-status.sh
    font_size = 18
    font_family = "JetBrainsMono Nerd Font"
    position = -45, 155
    halign = right
    valign = bottom
}

# MEDIA STATE
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/hyprlock/media-state.sh
    font_size = 18
    font_family = "JetBrainsMono Nerd Font"
    position = -45, 110
    halign = right
    valign = bottom
}

# MEDIA PREVIOUS
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/hyprlock/media-prev.sh
    font_size = 22
    font_family = "JetBrainsMono Nerd Font"
    position = -145, 50
    halign = right
    valign = bottom
    onclick = playerctl previous
}

# MEDIA PLAY/PAUSE
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/hyprlock/media-playpause.sh
    font_size = 22
    font_family = "JetBrainsMono Nerd Font"
    position = -95, 50
    halign = right
    valign = bottom
    onclick = playerctl play-pause
}

# MEDIA NEXT
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/hyprlock/media-next.sh
    font_size = 22
    font_family = "JetBrainsMono Nerd Font"
    position = -45, 50
    halign = right
    valign = bottom
    onclick = playerctl next
}
